on: [push]
name: Build Jupyter notebook Docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: make jupyter-docker
